## AYU LESTARI GUNAWAN
## 2109106054

In [122]:
import tensorflow as tf

### Tensor shape(5,5) dengan nilai random disimpan dalam random_tensor

In [47]:
random_tensor=tf.random.normal((5,5),mean=10,stddev=1,seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 9.898933 , 10.469209 ,  8.929651 , 10.860571 ,  9.208693 ],
       [10.09046  , 10.948287 , 10.472153 , 12.038057 ,  9.544712 ],
       [ 9.525359 ,  9.937083 , 10.397867 , 10.228864 ,  9.9692745],
       [ 9.718425 , 10.795831 , 10.713365 ,  9.718656 , 10.979879 ],
       [11.057077 ,  9.543067 ,  9.698736 , 11.034456 ,  8.962647 ]],
      dtype=float32)>

Tensor shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [45]:
prime_tensor=tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,
                          71,73,79,83,89,97,101],shape=(5,5),dtype=tf.float32)

### Dimensi dari prime_tensor dan random_tensor

In [125]:
print('Dimensi Random_Tensor: ',random_tensor.shape)
print('Dimensi Prime_Tensor: ',prime_tensor.shape)

Dimensi Random_Tensor:  (5, 5)
Dimensi Prime_Tensor:  (5, 5)


### Hasil dari perhitungan aritmetika 2 variable

In [124]:
print("Penjumlahan:\n" ,tf.add(random_tensor,prime_tensor).numpy())
print("\nPengurangan:\n" ,tf.subtract(random_tensor,prime_tensor).numpy())
print("\nPerkalian Matrix:\n" ,tf.matmul(random_tensor,prime_tensor).numpy())
print("\nPangkat:\n" ,tf.pow(prime_tensor,random_tensor).numpy())
print("\nPembagian:\n" ,tf.divide(random_tensor,prime_tensor).numpy())

Penjumlahan:
 [[ 11.898933  13.469209  13.929651  17.86057   20.208693]
 [ 23.09046   27.948288  29.472153  35.038055  38.544712]
 [ 40.52536   46.937084  51.397865  53.228863  56.969276]
 [ 62.718426  69.79583   71.71336   80.71866   83.97988 ]
 [ 90.057076  92.54307   98.69874  108.034454 109.96265 ]]

Pengurangan:
 [[  7.8989334   7.4692087   3.9296513   3.860571   -1.7913074]
 [ -2.9095402  -6.051713   -8.527847  -10.961943  -19.455288 ]
 [-21.47464   -27.062916  -30.602133  -32.771137  -37.030724 ]
 [-43.281574  -48.20417   -50.286636  -61.281345  -62.02012  ]
 [-67.942924  -73.45693   -79.30126   -85.965546  -92.03735  ]]

Perkalian Matrix:
 [[1735.8137 1943.1656 2096.5938 2358.403  2555.0884]
 [1879.1947 2106.3184 2271.629  2553.2856 2763.4807]
 [1800.2692 2013.1803 2173.97   2435.6077 2635.2578]
 [1874.3962 2093.8096 2263.008  2532.0806 2741.9395]
 [1739.7102 1949.1893 2105.0293 2366.7588 2564.96  ]]

Pangkat:
 [[9.5471967e+02 9.8873977e+04 1.7440478e+06 1.5074648e+09 3.8892429

### Nilai maksimal dan minimal dari variable random_tensor

Nilai Max Keseluruhan dan Pada Masing2 Kolom

In [102]:
Max_all=tf.math.reduce_max(random_tensor)
print('Max Keseluruhan:', Max_all.numpy())
print('Max Per Kolom:')
for i,x in enumerate(tf.argmax(random_tensor)):
    print(f' kolom: {i}  isi: {random_tensor[x,i]}')

Max Keseluruhan: 12.038057
Max Per Kolom:
 kolom: 0  isi: 11.057077407836914
 kolom: 1  isi: 10.948287010192871
 kolom: 2  isi: 10.713364601135254
 kolom: 3  isi: 12.038057327270508
 kolom: 4  isi: 10.979879379272461


Nilai Min Keseluruhan dan Pada Masing2 Kolom

In [101]:
Min_all=tf.math.reduce_min(random_tensor)
print('Min Keseluruhan:', Min_all.numpy())
print('Min Per Kolom:')
for i,x in enumerate(tf.argmin(random_tensor)):
    print(f' kolom: {i}  isi: {random_tensor[x,i]}')

Min Keseluruhan: 8.929651
Min Per Kolom:
 kolom: 0  isi: 9.525359153747559
 kolom: 1  isi: 9.54306697845459
 kolom: 2  isi: 8.929651260375977
 kolom: 3  isi: 9.718655586242676
 kolom: 4  isi: 8.962647438049316


### Hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [109]:
concat=tf.concat([random_tensor,prime_tensor],axis=1)
concat.numpy()

array([[  9.898933 ,  10.469209 ,   8.929651 ,  10.860571 ,   9.208693 ,
          2.       ,   3.       ,   5.       ,   7.       ,  11.       ],
       [ 10.09046  ,  10.948287 ,  10.472153 ,  12.038057 ,   9.544712 ,
         13.       ,  17.       ,  19.       ,  23.       ,  29.       ],
       [  9.525359 ,   9.937083 ,  10.397867 ,  10.228864 ,   9.9692745,
         31.       ,  37.       ,  41.       ,  43.       ,  47.       ],
       [  9.718425 ,  10.795831 ,  10.713365 ,   9.718656 ,  10.979879 ,
         53.       ,  59.       ,  61.       ,  71.       ,  73.       ],
       [ 11.057077 ,   9.543067 ,   9.698736 ,  11.034456 ,   8.962647 ,
         79.       ,  83.       ,  89.       ,  97.       , 101.       ]],
      dtype=float32)

### Hasil sorting dari kedua variable. (descending)

Sorting hasil concat

In [121]:
print("Concat Sort:\n",tf.sort(concat,direction="DESCENDING").numpy())

Concat Sort:
 [[ 11.         10.860571   10.469209    9.898933    9.208693    8.929651
    7.          5.          3.          2.       ]
 [ 29.         23.         19.         17.         13.         12.038057
   10.948287   10.472153   10.09046     9.544712 ]
 [ 47.         43.         41.         37.         31.         10.397867
   10.228864    9.9692745   9.937083    9.525359 ]
 [ 73.         71.         61.         59.         53.         10.979879
   10.795831   10.713365    9.718656    9.718425 ]
 [101.         97.         89.         83.         79.         11.057077
   11.034456    9.698736    9.543067    8.962647 ]]


Sorting masing2 variabel

In [119]:
print("Random_Tensor Sort:\n",tf.sort(random_tensor,direction="DESCENDING").numpy())
print("\nRandom_Tensor Sort:\n",tf.sort(prime_tensor,direction="DESCENDING").numpy())

Random_Tensor Sort:
 [[10.860571  10.469209   9.898933   9.208693   8.929651 ]
 [12.038057  10.948287  10.472153  10.09046    9.544712 ]
 [10.397867  10.228864   9.9692745  9.937083   9.525359 ]
 [10.979879  10.795831  10.713365   9.718656   9.718425 ]
 [11.057077  11.034456   9.698736   9.543067   8.962647 ]]

Random_Tensor Sort:
 [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]]
